# Welcome to Jekyll!
#
sass_dir: bower_components/bootstrap-sass/assets/stylesheets
# Site settings
title: My awesome Portfolio
email: jo_92jo@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.google.com" # the base hostname & protocol for your site
twitter_username: jolejo
github_username:  jolejo
google_username: jolejo

permalink: /:categories/:title

links:
    - title: About
      url: /about
    - title: Work
      url: /work
    - title: Articles
      url: /article
    - title: Hire me
      url: /hire-me



# Build settings
markdown: kramdown
